### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by m-ocean-it** [joeybaker/1pif-to-csv#1]
```
1pif-to-csv ~/Desktop/personal.1pif > ~/Desktop/personal.csv
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:202:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:539:5) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

I'm just trying to use your thingy :)

**Comment by joeybaker** [comment]
Oh man. I haven't touched this repo in forever. I bet it needs a really old node version. Streams API has changed like 3 times since I wrote this. I'd happily merge a PR to fix this.

**Comment by m-ocean-it** [comment]
Oh, okay, thanks!
